# .devcontainer/docker-compose.yml

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: ma_project_app
    
    volumes:
      - ../:/workspace:cached 
    
    env_file:
      - ../.env
    
    depends_on:
      postgres_db:
        condition: service_healthy 

    ports:
      - "8501:8501"   
        
  postgres_db:
    image: postgres:14-alpine
    container_name: ma_project_db
    restart: always
    ports:
      - "5432:5432" 
    env_file:
      - ../.env
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ma_pipeline_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_volume: 